apiVersion: 1
datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    isDefault: true
    access: proxy
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: clickhouse
      defaultDatabase: commerce
      tlsSkipVerify: false
    secureJsonData:
      password: clickhouse